const SET_PERSON_ID = "SET_PERSON_ID";
const SET_PERSONAL_DATA = "SET_PERSONAL_DATA";
const SET_SOCIAL_DATA = "SET_SOCIAL_DATA";
const SET_EDUCATION_DATA = "SET_EDUCATION_DATA";
const SET_COURSE_DATA = "SET_COURSE_DATA";
const SET_EXPERIENCE_DATA = "SET_EXPERIENCE_DATA";
const SET_SKILL_DATA = "SET_SKILL_DATA";

const StoreTypes = {
  SET_PERSON_ID,
  SET_PERSONAL_DATA,
  SET_SOCIAL_DATA,
  SET_EDUCATION_DATA,
  SET_COURSE_DATA,
  SET_EXPERIENCE_DATA,
  SET_SKILL_DATA,
};

export default StoreTypes;
